"""Add status to blog_posts

Revision ID: 23b2c8a30219
Revises: f64c52c940af
Create Date: 2025-02-07 10:48:02.213003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23b2c8a30219'
down_revision = 'f64c52c940af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_posts', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_posts', sa.Column('status', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
