"""Initial migration

Revision ID: bdd2ea2b56cb
Revises: 66c335c12b24
Create Date: 2025-02-06 10:58:57.436075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdd2ea2b56cb'
down_revision = '66c335c12b24'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
