"""Add status to blog_posts

Revision ID: f64c52c940af
Revises: bdd2ea2b56cb
Create Date: 2025-02-07 10:14:16.987797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f64c52c940af'
down_revision = 'bdd2ea2b56cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_posts', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_posts', 'status')
    # ### end Alembic commands ###
